### ISSUE TITLE
Does not take the correct labels

### ISSUE THREAD

**Issue by andreaTierra** [tierratelematics/ninjagoat-translations#2]
Hi, I have a  problem
Last time i updated ninjagoat-translations from "1.0.1" to "3.1.0" but now the translations do not work.
I have the language browser sets in Japanese and ninjagoat-translation understands it but it gets the label in english.
And the endpoint it's correct, I want ask, in the new version the method for get the labels did it change?

**Comment by lazyoft** [comment]
Hi,
starting from major 2.0.0 the way in which ninjagoat-translations retrieves the language files has changed, in order to accomodate an optimization for delivering language files over a CDN, without having to require a specific server anymore. Due to this the language files are now requested with the ".json" suffix, which I think is what is forcing your system to fall back to the english language.
The solution could either be to just stick to the previous version of ninjagoat-translations or change your node application serving language files so that it will accomodate the .json suffix on the request.

**Comment by andreaTierra** [comment]
Ok, only a last question I can use the "ninjagoat-translation 1.0.1" with "ninjagoat 2.3.4" and "ninjagoat-auth 2.4.1", are they compatible?

**Comment by lazyoft** [comment]
Modules should be independent among itself. Most specifically the translation module uses the HttpClient from ninjagoat which has been unchanged for a long while, therefore it should work. I guess that the only way to be sure is trying that :)

**Comment by andreaTierra** [comment]
Ok thank you so much
